//Array de palabras para usar durante toda la ejecucion
const array = [
    'aboya',
    'abran',
    'abras',
    'acles',
    'acoja',
    'acojo',
    'acres',
    'actas',
    'actos',
    'acuna',
    'acune',
    'acuno',
    'acuso',
    'acuña',
    'acuñe',
    'acuño',
    'afeas',
    'aguda',
    'agudo',
    'albas',
    'albos',
    'alces',
    'algas',
    'almas',
    'alojo',
    'altas',
    'altos',
    'amiga',
    'amigo',
    'amina',
    'ancas',
    'andas',
    'andes',
    'anima',
    'aojar',
    'aojas',
    'aojos',
    'apoda',
    'apodo',
    'aptas',
    'arces',
    'arcos',
    'ardan',
    'ardas',
    'ardes',
    'arias',
    'arios',
    'arlos',
    'armes',
    'arpas',
    'aruñe',
    'aruño',
    'ascos',
    'asees',
    'aseos',
    'asolo',
    'atoja',
    'atojo',
    'avale',
    'avara',
    'bagas',
    'bajas',
    'balas',
    'bales',
    'bares',
    'barre',
    'basca',
    'baste',
    'batas',
    'bates',
    'bayas',
    'bañas',
    'bañes',
    'baños',
    'bebed',
    'bebes',
    'besen',
    'beses',
    'besos',
    'betas',
    'bodas',
    'bonos',
    'borre',
    'botad',
    'botan',
    'botas',
    'boten',
    'botes',
    'boyas',
    'bramo',
    'bruta',
    'bruño',
    'bulas',
    'buses',
    'caceo',
    'cagas',
    'cajas',
    'calce',
    'cales',
    'callo',
    'calme',
    'calmo',
    'canas',
    'canes',
    'cansa',
    'capas',
    'capta',
    'capto',
    'caros',
    'casan',
    'casas',
    'casca',
    'casos',
    'catas',
    'cause',
    'cavas',
    'cavos',
    'cazan',
    'cazas',
    'cazos',
    'cañas',
    'cañeo',
    'cebos',
    'ceded',
    'cedes',
    'cefos',
    'cejas',
    'celes',
    'cenas',
    'cepas',
    'ceras',
    'cerdo',
    'ceros',
    'chefs',
    'ciega',
    'cines',
    'clamo',
    'clava',
    'clubs',
    'coces',
    'codeo',
    'coged',
    'cogen',
    'coger',
    'coges',
    'cojas',
    'cojin',
    'cojos',
    'colas',
    'coles',
    'colma',
    'coman',
    'comas',
    'comed',
    'comes',
    'conos',
    'copas',
    'copos',
    'copta',
    'coral',
    'coras',
    'corea',
    'corra',
    'corre',
    'corro',
    'corsa',
    'cosas',
    'creas',
    'crees',
    'croar',
    'cruje',
    'cubas',
    'cubos',
    'cucos',
    'cuida',
    'cuide',
    'culos',
    'culta',
    'cunas',
    'cural',
    'curas',
    'curdo',
    'cures',
    'curio',
    'cuñas',
    'dagas',
    'datos',
    'dañes',
    'daños',
    'debas',
    'debed',
    'debes',
    'dedos',
    'dejas',
    'densa',
    'dijes',
    'diles',
    'doman',
    'domas',
    'domes',
    'domos',
    'donan',
    'donas',
    'donen',
    'dones',
    'dores',
    'doria',
    'dorio',
    'dotas',
    'dotes',
    'doñas',
    'drupa',
    'dudan',
    'dunas',
    'dures',
    'duros',
    'echas',
    'eches',
    'edita',
    'eleve',
    'ellos',
    'emana',
    'emoji',
    'enoja',
    'enojo',
    'entes',
    'erizo',
    'errar',
    'erres',
    'estad',
    'estas',
    'euros',
    'evita',
    'falle',
    'falos',
    'ferio',
    'fetos',
    'ficad',
    'ficas',
    'fijas',
    'filas',
    'files',
    'fique',
    'focos',
    'folla',
    'forme',
    'fosil',
    'fosos',
    'fotos',
    'frita',
    'fugas',
    'fumes',
    'gafas',
    'galas',
    'galos',
    'ganes',
    'gases',
    'gatos',
    'genes',
    'gimen',
    'gimes',
    'giras',
    'giros',
    'godas',
    'godos',
    'goles',
    'gorda',
    'gorra',
    'grabe',
    'grave',
    'grite',
    'groar',
    'habas',
    'habed',
    'hacen',
    'haces',
    'hagan',
    'hagas',
    'halan',
    'halas',
    'hallo',
    'harte',
    'hayan',
    'hayas',
    'heces',
    'hecha',
    'hecho',
    'hemos',
    'hiero',
    'hijas',
    'hilan',
    'hilos',
    'hinca',
    'hipos',
    'hoces',
    'hojas',
    'huera',
    'huero',
    'hunas',
    'hunos',
    'hurgo',
    'husos',
    'ibais',
    'ideas',
    'isbas',
    'islas',
    'jefes',
    'jemal',
    'jemes',
    'jerga',
    'jodas',
    'jodes',
    'jonia',
    'joyas',
    'joyel',
    'jugos',
    'jujeo',
    'jures',
    'kanes',
    'kunas',
    'kurda',
    'labes',
    'labia',
    'labre',
    'lacra',
    'lacta',
    'lados',
    'ladro',
    'lagos',
    'lamas',
    'lamen',
    'lames',
    'lapas',
    'larga',
    'latas',
    'laves',
    'laxas',
    'laxos',
    'lazan',
    'lazos',
    'legas',
    'legos',
    'lejos',
    'lemas',
    'lenta',
    'levas',
    'leves',
    'leyes',
    'libia',
    'lides',
    'limas',
    'linda',
    'liras',
    'lises',
    'locas',
    'locha',
    'locos',
    'lomos',
    'lores',
    'loros',
    'losas',
    'loteo',
    'lozas',
    'luces',
    'luche',
    'lucho',
    'lunas',
    'lusas',
    'lusos',
    'maceo',
    'magos',
    'malas',
    'males',
    'malos',
    'mamas',
    'manas',
    'manca',
    'manda',
    'manos',
    'mapas',
    'mares',
    'masco',
    'mases',
    'matas',
    'mates',
    'mayas',
    'mazos',
    'mañas',
    'meaba',
    'mecen',
    'meces',
    'menes',
    'meras',
    'meros',
    'mesas',
    'mesen',
    'meses',
    'metas',
    'metes',
    'mezas',
    'midas',
    'migro',
    'miles',
    'minas',
    'mines',
    'miras',
    'miren',
    'mires',
    'misad',
    'misas',
    'misma',
    'mista',
    'mitos',
    'mitro',
    'mocos',
    'modas',
    'modos',
    'mofes',
    'mojar',
    'mojas',
    'mojen',
    'mojos',
    'molas',
    'moles',
    'monas',
    'monos',
    'moras',
    'mores',
    'moros',
    'morro',
    'moved',
    'mozas',
    'moños',
    'mucas',
    'mucos',
    'mudas',
    'mudos',
    'mueve',
    'mugen',
    'muges',
    'mugid',
    'mujan',
    'mujas',
    'mulas',
    'multe',
    'muros',
    'nabos',
    'nadas',
    'nades',
    'narre',
    'naves',
    'nazis',
    'necia',
    'netos',
    'nevar',
    'niños',
    'nomos',
    'notas',
    'notes',
    'nubes',
    'nucas',
    'nudas',
    'nudos',
    'nueva',
    'nuevo',
    'nulas',
    'nulos',
    'obras',
    'odias',
    'odios',
    'ogros',
    'ollas',
    'ondas',
    'onzas',
    'opera',
    'optas',
    'orcas',
    'orden',
    'ornan',
    'oseas',
    'otras',
    'ovulo',
    'pacas',
    'pacen',
    'pacta',
    'pague',
    'pajas',
    'pajes',
    'palas',
    'palme',
    'palos',
    'palpa',
    'panes',
    'paras',
    'parda',
    'paren',
    'pares',
    'parta',
    'pasas',
    'pasen',
    'pases',
    'patas',
    'patea',
    'patos',
    'pañal',
    'pecas',
    'peces',
    'pedos',
    'pegas',
    'pegue',
    'peine',
    'peino',
    'pelos',
    'penan',
    'penas',
    'penda',
    'pende',
    'penen',
    'penes',
    'peras',
    'peros',
    'pesad',
    'pesas',
    'pesen',
    'peses',
    'pesos',
    'petas',
    'peñas',
    'pican',
    'pidas',
    'pides',
    'pines',
    'pipas',
    'pisad',
    'pises',
    'plena',
    'pleno',
    'pocas',
    'pocos',
    'podas',
    'poded',
    'poder',
    'podes',
    'poned',
    'ponen',
    'poner',
    'pones',
    'ponga',
    'porfa',
    'posee',
    'posen',
    'poses',
    'posos',
    'potos',
    'poyas',
    'pozos',
    'prado',
    'preña',
    'preño',
    'pueda',
    'puede',
    'puedo',
    'pujan',
    'pujas',
    'pujen',
    'pulen',
    'pumas',
    'puras',
    'puros',
    'putas',
    'queme',
    'quemo',
    'queso',
    'quise',
    'quiso',
    'quito',
    'rabos',
    'ralbe',
    'ramos',
    'rapas',
    'rasco',
    'ratas',
    'ratos',
    'reces',
    'recia',
    'redes',
    'rejas',
    'remas',
    'remes',
    'remos',
    'rento',
    'reses',
    'reste',
    'retes',
    'retos',
    'reyes',
    'rezan',
    'rezas',
    'rices',
    'rifas',
    'rimas',
    'rimen',
    'rimes',
    'rinda',
    'roban',
    'robes',
    'rocas',
    'rodas',
    'rojas',
    'rojos',
    'rolla',
    'romas',
    'romos',
    'rompe',
    'rones',
    'rotas',
    'rotos',
    'royas',
    'royos',
    'rudos',
    'rugen',
    'ruges',
    'rujan',
    'runas',
    'rusas',
    'rusos',
    'ruñas',
    'sabia',
    'sacan',
    'sacas',
    'sacos',
    'salga',
    'salgo',
    'salta',
    'salva',
    'salve',
    'sanad',
    'sanas',
    'sapos',
    'sañas',
    'sebos',
    'sedes',
    'sepas',
    'seres',
    'seria',
    'setas',
    'siega',
    'siego',
    'sigan',
    'siria',
    'siseo',
    'soban',
    'sobas',
    'sobes',
    'soles',
    'sonad',
    'sonar',
    'soñad',
    'soñar',
    'sordo',
    'sorda',
    'subas',
    'subes',
    'sucia',
    'sucre',
    'sudan',
    'sudar',
    'sudas',
    'suela',
    'suele',
    'suena',
    'suene',
    'sueno',
    'sueña',
    'sueñe',
    'sueño',
    'suiza',
    'sumas',
    'sushi',
    'tacos',
    'talas',
    'tapas',
    'tapes',
    'tejas',
    'temas',
    'temen',
    'temes',
    'tened',
    'tenga',
    'tengo',
    'tenia',
    'tensa',
    'terca',
    'tersa',
    'terse',
    'testo',
    'tetar',
    'tetas',
    'tiene',
    'times',
    'tipos',
    'tiras',
    'tiros',
    'togas',
    'tomad',
    'toman',
    'tomas',
    'tomes',
    'tonos',
    'tonta',
    'topas',
    'topos',
    'torpe',
    'tosed',
    'traed',
    'traen',
    'traer',
    'traes',
    'trajo',
    'tubos',
    'tunas',
    'untes',
    'urdas',
    'urnas',
    'usaos',
    'usate',
    'uñoso',
    'vacan',
    'vacas',
    'vagas',
    'vagos',
    'vague',
    'vales',
    'valga',
    'valgo',
    'valsa',
    'valse',
    'vamos',
    'vasca',
    'vasos',
    'vasta',
    'vates',
    'vayan',
    'vayas',
    'veces',
    'vedas',
    'velas',
    'veles',
    'velos',
    'vemos',
    'venas',
    'vengo',
    'vetas',
    'vidas',
    'viera',
    'vigas',
    'vinos',
    'vires',
    'voces',
    'volar',
    'votad',
    'votan',
    'votar',
    'votas',
    'voten',
    'votes',
    'votos',
    'wikis',
    'wones',
    'yates',
    'yemas',
    'yendo',
    'yenes',
    'yesca',
    'yogur',
    'yugos',
    'zacas',
    'zarca',
    'zares',
    'zetas',
    'zonas',
    'zorro',
    'zurda',
    'zurro',
    'ñames',
    'ñutas',
    'ñutos'
]

//event listener que se activa cuando toda la pagina  se ha cargado y llama a la funcion inicio
addEventListener("load", inicio, false);
let palabra = '';


//funcion que cuando la pagina ha cargado comienza a ejecutarse
function inicio() {
    let conjuntoTeclas = document.getElementsByClassName("key");//array de todas las teclas del teclado .key

    for (let letra of conjuntoTeclas) {
        letra.addEventListener('click', escribirLetra, false);//Por cada letra del teclado añadimos un eventListener que llamara a la funcion escribirTecla
    }

}

//Declaramos una serie de variables que usaremos para la ejecucion
let contadorFilas = 0;//Hace referencia a la fila en la que nos encontramos desde 0 hasta 5 --> 6 filas

let contadorCeldas = 0;//Hace referencia a la celda en la que nos encontramos dentro de una fila de 0 -- 4 --> 5 celdas

//Generamos un numero aleatorio segun el tamaño del array
let num = parseInt((Math.random() * array.length))
//Seleccionamos la palabra en la posicion aleatoria
palabra = array[num].toUpperCase();

//Funcion principal para escribir la letra
function escribirLetra() {

    let fila_tabla = document.getElementsByTagName("tr");//Conjunto de todas las filas de nuestro panel
    let fila = fila_tabla[contadorFilas];//fila en la que nos encontramos
    let celdas = fila.children;//conjunto de celdas en la fila en la que nos encontramos


    if (contadorCeldas == 5) {
        /**
         * Nuestra logica se basará en hacer comprobaciones una vez que se haya escrito la palabra completa.
         * Una vez que la palabra esta completa solo podremos borrar letras o pulsar enter para comprobar nuestro
         * intento, eso es lo que hacemos con el primer condicional que tenemos.
         * 
         */
        if (this.innerHTML != 'ENT' && this.innerHTML != 'DEL') {
            alert('SOLO PUEDES PULSAR ENTER O DEL');
        } else {
            //En caso de que pulsemos del borramos sustituyendo la letra por un '' y volviendo hacia atras para escribir sobre la borrada
            if (this.innerHTML == 'DEL') {
                celdas[contadorCeldas - 1].innerHTML = '';
                contadorCeldas--;
                //En caso de que no sea del obligatoriamente sera ENTER
                //por lo que deberemos empezar a comprobar la palabra   
            } else {

                let contadorAciertos = 0;//Almacenaremos las letras correctas por cada intento
                //Creamos dos arrays que usaremos para hacer la comprobación entre la palabra correcta y el intento
                let palabra_array = [5];//PALABRA CORRECTA 
                let aux_palabra_array = [5];//PALABRA CORRECTA AUXILIAR

                //LOS RELLENAMOS CON LA PALABRA CORRECTA
                for (var i = 0; i < 5; i++) {
                    palabra_array[i] = palabra.charAt(i);
                    aux_palabra_array[i] = palabra.charAt(i);
                }
                /**
                 * 1º BUCLE EN EL QUE SOLO COMPROBAREMOS SI LA COINCIDE LETRA Y POSICION
                 */
                for (var i = 0; i < 5; i++) {
                    if (palabra_array[i] == celdas[i].innerHTML) {//letra en la palabra correcta == valor introducido en esa posicion
                        celdas[i].className += "verde";//añadimos la clase verde a la celda que le cambiara el color
                        //Y tambien cambiamos el color del teclado por el verde haciendo uso de valores del id
                        document.getElementById(celdas[i].innerHTML).className = "keyVerde";
                        //Sustituimos en nuestro array auxiliar las posiciones correctas por - asi conseguimos
                        //Que a la hora de comprobar amarillas y grises los problemas con las verdes desaparezcan
                        aux_palabra_array[i] = '-';
                        contadorAciertos++;//Aumentamos el contador de aciertos
                    }
                }
                /**
                 * 2º BUCLE EN EL QUE COMPROBAREMOS SI SON AMARILLAS O GRIS
                 * AMARILLA -> CORRECTA PERO NO EN ESA POSICION
                 * GRIS     -> INCORRECTA
                 * 
                 * Cabe recalcar que en nuestro array_aux ya solo tenemos las letras amarillas y grises
                 */
                for (var i = 0; i < 5; i++) {
                    //En caso de que en el array este la letra intentada sabemos que 100% es amarilla
                    if (aux_palabra_array.includes(celdas[i].innerHTML)) {
                        //Si justo esa posicion no es un guión, cambiamos el color al boton del teclado y la celda
                        if (aux_palabra_array[i] != '-') {
                            celdas[i].className += "amarillo";
                            document.getElementById(celdas[i].innerHTML).className = "keyAmarillo";
                        }
                        //Si no la contiene es 100% gris siempre que no sea un guion  
                    } else if (aux_palabra_array[i] != '-') {
                        //Cambiamos color en teclado y celda
                        celdas[i].className += "gris";
                        document.getElementById(celdas[i].innerHTML).className = "keyGris";
                    }

                }
                /**
                 * REALIZADAS TODAS LAS COMPROBACIONES EMPEZAMOS A COMPARAR EL CONTADOR DE ACIERTOS
                 * SI LA PALABRA COINCIDE EN SU TOTALIDAD TENDREMOS 5 ACIERTOS POR LO QUE HABREMOS GANADO Y SE FINALIZA LA PARTIDA
                 */
                if (contadorAciertos == 5) {
                    alert('Enhorabuena acertas la palabra !!')
                    location.reload();//RECARGAMOS LA VENTANA 
                    /**
                     * EN CASO CONTRARIO SI LA FILA ES LA ULTIMA HAS PERDIDO, SI NO PUEDES SEGUIR INTENTANDO COMBINACIONES
                     */
                } else {
                    if (contadorFilas == 5) {
                        alert('Lo siento has perdido :( la palabra correcta era' + palabra);
                        location.reload();//RECARGAMOS LA VENTANA 

                    }
                    /**
                     * IMPRIMIMOS TAMBIEN LOS INTENTOS FALLIDOS
                     */
                    let intentoPalabra = '';//Palabra fallada
                    //La rellenamos con el intento que se ha realizado
                    for (var i = 0; i < 5; i++) {
                        intentoPalabra += celdas[i].innerHTML;
                    }

                    var div = document.createElement('div');//Creamos un elemento div
                    div.innerHTML = intentoPalabra + ' NO ES CORRECTO';//Añadimos texto
                    document.getElementById('fallos').appendChild(div);//Y se lo añadmios al elemento con id fallos
                }
                contadorFilas++;//Aumentamos la fila
                contadorCeldas = 0;//Y empezamos otra vez con la celda en 0
            }
        }
    }
    else {
        /*BORRAR UNA CELDA SIN QUE SEA LA 5ta posicion*/
        if (this.innerHTML == 'DEL') {
            if (contadorCeldas == 0) {
                alert('NO PUEDES BORRAR MAS');//No se puede borrar si no hay nada escrito
            } else {
                celdas[contadorCeldas - 1].innerHTML = '';//Sustituimos por ''
                contadorCeldas--;//nos posicionamos en la anterior y ya habríamos borrado
            }

            /**
             * SE REFIERE A PULSAR CUALQUIER OTRA TECLA
             * ES DECIR ESCRIBIR UNA LERTRA
             */
        } else if (this.innerHTML != 'ENT') {
            celdas[contadorCeldas].innerHTML = this.innerHTML;//Cogemos el valor de la tecla pulsada y se lo asignamos a la celda
            contadorCeldas++;//Sumamos 1 a la celda
        }
    }

}
